### ISSUE TITLE
Can't get the real code of faster_mix_k_means_pytorch.py

### ISSUE THREAD

**Issue by lzjgd611** [DTennant/GPC#1]
I get the "faster_mix_k_means_pytorch.py" from https://github.com/sgvaze/generalized-category-discovery, but some bugs occur. 
For example, I can't find the function named "predict()" in the faster_mix_k_means_pytorch.py in https://github.com/sgvaze/generalized-category-discovery, which will cause a bug that the sentence "preds = kmeans.predict(test_feats)" in [gmm_sm.py] line 625 dose not work.

**Comment by yinjiexidian** [comment]
> [我从https://github.com/sgvaze/generalized-category-discovery](https://github.com/sgvaze/generalized-category-discovery)中获取了 faster_mix_k_means_pytorch.py ​​，但是出现了一些 bug，比如在https://github.com/sgvaze/generalized-category-discovery 中的 faster_mix_k_means_pytorch.py​​ 中找不到名为 predict() 的函数，导致 [gmm_sm.py] 第 625 行的语句 preds = kmeans.predict(test_feats) 无法正常工作。[](https://github.com/sgvaze/generalized-category-discovery)

I encountered the same issue. Did you manage to resolve it?

**Comment by yinjiexidian** [comment]
> [我从https://github.com/sgvaze/generalized-category-discovery](https://github.com/sgvaze/generalized-category-discovery)中获取了 faster_mix_k_means_pytorch.py ​​，但是出现了一些 bug，比如在https://github.com/sgvaze/generalized-category-discovery 中的 faster_mix_k_means_pytorch.py​​ 中找不到名为 predict() 的函数，导致 [gmm_sm.py] 第 625 行的语句 preds = kmeans.predict(test_feats) 无法正常工作。[](https://github.com/sgvaze/generalized-category-discovery)

I encountered the same issue. Did you manage to resolve it?

**Comment by yinjiexidian** [comment]
> I get the "faster_mix_k_means_pytorch.py" from https://github.com/sgvaze/generalized-category-discovery, but some bugs occur. For example, I can't find the function named "predict()" in the faster_mix_k_means_pytorch.py in https://github.com/sgvaze/generalized-category-discovery, which will cause a bug that the sentence "preds = kmeans.predict(test_feats)" in [gmm_sm.py] line 625 dose not work.
I encountered a similar problem. Can you provide the "faster_mix_k_means_pytorch.py" file?

**Comment by DTennant** [comment]
This should have been solved by #3 now
